version = 0.1

[default.deploy.parameters]
stack_name = "sam"
resolve_s3 = false
s3_prefix = "sam/artifacts"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
