name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      api-url: ${{ steps.get-api.outputs.api_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build SAM app
        run: sam build --use-container

      - name: Deploy SAM app
        run: |
          sam deploy \
            --no-confirm-changeset \
            --stack-name campaign-manager \
            --capabilities CAPABILITY_IAM \
            --s3-bucket "${{ secrets.AWS_SAM_ARTIFACT_BUCKET }}"

      - name: Fetch API URL from CloudFormation
        id: get-api
        run: |
          API_URL=$(aws cloudformation describe-stacks \
            --stack-name campaign-manager \
            --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
            --output text)

          echo "API URL = $API_URL"

          echo "$API_URL" > api_url.txt
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Upload API URL artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-api-url
          path: api_url.txt
