name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Deploy Backend"]
    types:
      - completed

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Download backend API URL
        uses: actions/download-artifact@v4
        with:
          name: backend-api-url

      - name: Read API URL
        id: read-api
        run: |
          API_URL=$(cat api_url.txt)
          echo "API URL = $API_URL"
          echo "api_url=$API_URL" >> $GITHUB_OUTPUT

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install frontend deps
        run: |
          cd frontend
          npm ci

      - name: Build frontend with backend API URL
        run: |
          cd frontend
          REACT_APP_API_URL=${{ steps.read-api.outputs.api_url }} npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

